import '../../models/models.dart';

class DummyData {
  static final List<Course> courses = [
    Course(
      id: 'c1',
      kode: '2 PK 100',
      nama: 'Pendidikan Pancasila',
      sks: 2,
      semester: 1,
      dosen: 'Drs. H. M. Rusli, M.Si',
      dosenWa: '081234567890',
      hari: 'Senin',
      jamMulai: '15:30',
      jamSelesai: '17:00',
      ruangan: 'Ruang A2',
    ),
    Course(
      id: 'c2',
      kode: '2 PK 103',
      nama: 'Pendidikan Kewarganegaraan',
      sks: 2,
      semester: 1,
      dosen: 'Dra. Hj. Nurhaida, M.Pd',
      dosenWa: '081234567891',
      hari: 'Senin',
      jamMulai: '18:30',
      jamSelesai: '20:00',
      ruangan: 'Ruang B1',
    ),
    Course(
      id: 'c3',
      kode: '3 PK 101A',
      nama: 'Pendidikan Agama Islam *',
      sks: 3,
      semester: 1,
      dosen: 'Dr. H. Lukman Hakim, M.Ag',
      dosenWa: '081234567892',
      hari: 'Selasa',
      jamMulai: '15:30',
      jamSelesai: '17:45',
      ruangan: 'Ruang A1',
    ),
    Course(
      id: 'c4',
      kode: '3 PK 101B',
      nama: 'Pendidikan Agama Kristen *',
      sks: 3,
      semester: 1,
      dosen: 'Pdt. Dr. Markus Somba, M.Th',
      dosenWa: '081234567893',
      hari: 'Selasa',
      jamMulai: '15:30',
      jamSelesai: '17:45',
      ruangan: 'Ruang B1',
    ),
    Course(
      id: 'c5',
      kode: '2 PK 106',
      nama: 'Ilmu Kealaman Dasar *',
      sks: 2,
      semester: 1,
      dosen: 'Dr. Ir. Hendra Gunawan, M.Si',
      dosenWa: '081234567894',
      hari: 'Selasa',
      jamMulai: '18:30',
      jamSelesai: '20:45',
      ruangan: 'Ruang A2',
    ),
    Course(
      id: 'c6',
      kode: '3 PK 105',
      nama: 'Bahasa Indonesia *',
      sks: 3,
      semester: 1,
      dosen: 'Dra. Hj. Nurhayati, M.Hum',
      dosenWa: '081234567895',
      hari: 'Rabu',
      jamMulai: '15:30',
      jamSelesai: '17:45',
      ruangan: 'Ruang A2',
    ),
    Course(
      id: 'c7',
      kode: '3 PK 104',
      nama: 'Bahasa Inggris *',
      sks: 3,
      semester: 1,
      dosen: 'Farid Wajdi, S.Pd., M.A',
      dosenWa: '081234567896',
      hari: 'Kamis',
      jamMulai: '18:30',
      jamSelesai: '20:45',
      ruangan: 'Ruang A1',
    ),
    Course(
      id: 'c8',
      kode: '3 PK 201',
      nama: 'Pengantar Ilmu Politik *',
      sks: 3,
      semester: 1,
      dosen: 'Dr. Muhammad Rizal, S.IP., M.Si',
      dosenWa: '081234567897',
      hari: 'Jumat',
      jamMulai: '18:30',
      jamSelesai: '20:45',
      ruangan: 'Ruang B1',
    ),
  ];

  static final List<Assignment> assignments = [
    Assignment(
      id: 'a1',
      courseId: 'c6',
      courseName: 'Bahasa Indonesia *',
      judul: 'Penyusunan Esai Ilmiah & Review Literatur Ilkom',
      deskripsi: 'Format sitasi APA 7th style, minimal 1000 kata dengan topik Komunikasi Publik & Media.',
      kategori: 'Individu',
      deadline: DateTime.now().add(const Duration(days: 3, hours: 14)),
      linkPengumpulan: 'https://drive.google.com/unazlam-ilkom-tugas',
      status: 'sedang_dikerjakan',
    ),
    Assignment(
      id: 'a2',
      courseId: 'c8',
      courseName: 'Pengantar Ilmu Politik *',
      judul: 'Analisis Opini Publik dalam Komunikasi Politik Daerah',
      deskripsi: 'Analisis studi kasus pemberitaan pesta demokrasi di media massa lokal Sulawesi Tengah.',
      kategori: 'Proyek Praktikum',
      deadline: DateTime.now().add(const Duration(days: 6)),
      linkPengumpulan: 'https://classroom.google.com/unazlam',
      status: 'belum',
    ),
    Assignment(
      id: 'a3',
      courseId: 'c2',
      courseName: 'Pendidikan Kewarganegaraan',
      judul: 'Kajian Yuridis: Hak Asasi Manusia & Etika Media Digital',
      deskripsi: 'Makalah analisis kritis implementasi UU ITE terhadap kebebasan pers dan opini publik.',
      kategori: 'Individu',
      deadline: DateTime.now().add(const Duration(days: 9)),
      status: 'selesai',
    ),
    Assignment(
      id: 'a4',
      courseId: 'c7',
      courseName: 'Bahasa Inggris *',
      judul: 'Public Speaking: Informative Speech Presentation Script',
      deskripsi: 'Naskah pidato bahasa Inggris 3 menit mengenai Digital Literacy for Gen-Z mahasiswa komunikasi.',
      kategori: 'Individu',
      deadline: DateTime.now().add(const Duration(days: 12)),
      status: 'belum',
    ),
  ];

  static final List<Announcement> announcements = [
    Announcement(
      id: 'ann1',
      authorName: 'Irfan (Komti)',
      authorRole: 'Komandan Tingkat',
      judul: 'PENTING: Jadwal Kuliah Semester Ganjil T.A 2026/2027 Resmi Dimulai',
      isi: 'Halo rekan-rekan S1 Ilmu Komunikasi UNAZLAM! Perkuliahan semester ganjil telah resmi dimulai sesuai jadwal FISIP terbaru. Perhatikan jam sesi sore (15.30) dan malam (18.30) serta ruangan A1, A2, dan B1.',
      isPinned: true,
      kategori: 'Penting',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    Announcement(
      id: 'ann2',
      authorName: 'Biro Akademik FISIP',
      authorRole: 'Fakultas',
      judul: 'Ketentuan Ruangan Kuliah Pendidikan Agama (Selasa 15.30)',
      isi: 'Untuk perkuliahan Pendidikan Agama hari Selasa jam 15.30: Pendidikan Agama Islam berada di Ruang A1, sedangkan Pendidikan Agama Kristen berada di Ruang B1.',
      isPinned: false,
      kategori: 'Jadwal Kuliah',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Announcement(
      id: 'ann3',
      authorName: 'Nadia (Sekretaris)',
      authorRole: 'Pengurus Kelas',
      judul: 'Presensi Kehadiran 75% sebagai Syarat Mutlak Mengikuti UTS',
      isi: 'Diingatkan bahwa kehadiran minimal 75% (maksimal 4x dispensasi/izin/alpa dari total 16 sesi) adalah syarat mutlak mengikuti UTS. Pantau selalu tab Presensi di aplikasi.',
      isPinned: false,
      kategori: 'Penting',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
  ];

  static final List<ProjectGroup> projectGroups = [
    ProjectGroup(
      id: 'g1',
      namaKelompok: 'Kelompok 1 (Kajian Komunikasi Politik)',
      assignmentTitle: 'Analisis Opini Publik dalam Komunikasi Politik Daerah',
      courseName: 'Pengantar Ilmu Politik *',
      linkGDrive: 'https://drive.google.com/drive/folders/unazlam-kel1',
      members: [
        GroupMember(nama: 'Irfan Maulana (Ketua)', nim: '2210411001', peran: 'Ketua Tim & Koordinator Riset', peminatan: 'Komunikasi Politik'),
        GroupMember(nama: 'Anisa Putri Rahayu', nim: '2210411012', peran: 'Analis Konten Media', peminatan: 'Jurnalistik'),
        GroupMember(nama: 'Rizky Dwi Pratama', nim: '2210411025', peran: 'Penyusun Laporan & Infografis', peminatan: 'Public Relations'),
        GroupMember(nama: 'Tiara Amanda', nim: '2210411038', peran: 'Presenter & Notulen', peminatan: 'Public Relations'),
      ],
    ),
    ProjectGroup(
      id: 'g2',
      namaKelompok: 'Kelompok 2 (Literasi Bahasa & Media)',
      assignmentTitle: 'Penyusunan Esai Ilmiah & Review Literatur Ilkom',
      courseName: 'Bahasa Indonesia *',
      linkGDrive: 'https://drive.google.com/drive/folders/unazlam-kel2',
      members: [
        GroupMember(nama: 'Dimas Setiawan', nim: '2210411005', peran: 'Ketua Tim', peminatan: 'Public Relations'),
        GroupMember(nama: 'Siti Nurhaliza', nim: '2210411019', peran: 'Editor Bahasa & PUEBI', peminatan: 'Broadcasting'),
        GroupMember(nama: 'Farhan Alamsyah', nim: '2210411042', peran: 'Riset Kepustakaan & Sitasi', peminatan: 'Advertising'),
      ],
    ),
  ];

  static final List<CourseAttendance> attendanceRecords = [
    CourseAttendance(
      courseId: 'c1',
      courseName: 'Pendidikan Pancasila',
      sesiBerjalan: 7,
      hadir: 7,
      izin: 0,
      sakit: 0,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c2',
      courseName: 'Pendidikan Kewarganegaraan',
      sesiBerjalan: 7,
      hadir: 6,
      izin: 1,
      sakit: 0,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c3',
      courseName: 'Pendidikan Agama Islam *',
      sesiBerjalan: 7,
      hadir: 7,
      izin: 0,
      sakit: 0,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c5',
      courseName: 'Ilmu Kealaman Dasar *',
      sesiBerjalan: 7,
      hadir: 6,
      izin: 0,
      sakit: 1,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c6',
      courseName: 'Bahasa Indonesia *',
      sesiBerjalan: 7,
      hadir: 7,
      izin: 0,
      sakit: 0,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c7',
      courseName: 'Bahasa Inggris *',
      sesiBerjalan: 7,
      hadir: 5,
      izin: 1,
      sakit: 0,
      alpa: 1,
    ),
    CourseAttendance(
      courseId: 'c8',
      courseName: 'Pengantar Ilmu Politik *',
      sesiBerjalan: 7,
      hadir: 5,
      izin: 0,
      sakit: 0,
      alpa: 2, // Sisa toleransi alpa tinggal 2 kali
    ),
  ];

  static final List<ResourceItem> resources = [
    ResourceItem(
      id: 'r1',
      courseName: 'Pengantar Ilmu Politik *',
      pertemuanKe: 2,
      judul: 'Slide PPT: Konsep Dasar Kekuasaan & Komunikasi Politik',
      jenis: 'Slide PPT',
      linkUrl: 'https://docs.google.com/presentation/d/pol-unazlam',
    ),
    ResourceItem(
      id: 'r2',
      courseName: 'Bahasa Indonesia *',
      pertemuanKe: 4,
      judul: 'E-Book: Pedoman Umum Ejaan Bahasa Indonesia & Penulisan Ilmiah',
      jenis: 'E-Book',
      linkUrl: 'https://drive.google.com/file/d/puebi-handbook',
    ),
    ResourceItem(
      id: 'r3',
      courseName: 'Pendidikan Pancasila',
      pertemuanKe: 3,
      judul: 'Slide PPT: Pancasila sebagai Sistem Etika & Ideologi Terbuka',
      jenis: 'Slide PPT',
      linkUrl: 'https://drive.google.com/file/d/pancasila-ppt',
    ),
    ResourceItem(
      id: 'r4',
      courseName: 'Bahasa Inggris *',
      pertemuanKe: 5,
      judul: 'Bank Soal: Grammar & Public Speaking Practice Materials',
      jenis: 'Bank Soal',
      linkUrl: 'https://drive.google.com/file/d/bank-soal-bing',
    ),
    ResourceItem(
      id: 'r5',
      courseName: 'Ilmu Kealaman Dasar *',
      pertemuanKe: 3,
      judul: 'Jurnal Ilmiah: Pendekatan Sains & Ekologi Lingkungan Hidup Kontemporer',
      jenis: 'Jurnal Ilmiah',
      linkUrl: 'https://doi.org/10.1080/sample-journal',
    ),
  ];

  static final List<StudentProfile> students = [
    StudentProfile(
      id: 's1',
      nim: '2210411001',
      nama: 'Irfan Maulana (Komti)',
      email: 'irfan.maulana@student.unazlam.ac.id',
      noWa: '081234567890',
      peminatan: 'Broadcasting',
      role: 'komti',
      instagram: '@irfan.m',
      linkedin: 'linkedin.com/in/irfanmaulana',
    ),
    StudentProfile(
      id: 's2',
      nim: '2210411005',
      nama: 'Dimas Setiawan',
      email: 'dimas.setiawan@student.unazlam.ac.id',
      noWa: '082198765432',
      peminatan: 'Public Relations',
      role: 'mahasiswa',
      instagram: '@dimas_pr',
    ),
    StudentProfile(
      id: 's3',
      nim: '2210411012',
      nama: 'Anisa Putri Rahayu',
      email: 'anisa.putri@student.unazlam.ac.id',
      noWa: '081344556677',
      peminatan: 'Broadcasting',
      role: 'mahasiswa',
      instagram: '@anisaputri',
    ),
    StudentProfile(
      id: 's4',
      nim: '2210411019',
      nama: 'Siti Nurhaliza',
      email: 'siti.nurhaliza@student.unazlam.ac.id',
      noWa: '085733445566',
      peminatan: 'Public Relations',
      role: 'mahasiswa',
      instagram: '@sitinur',
    ),
    StudentProfile(
      id: 's5',
      nim: '2210411025',
      nama: 'Rizky Dwi Pratama',
      email: 'rizky.dwi@student.unazlam.ac.id',
      noWa: '087811223344',
      peminatan: 'Jurnalistik',
      role: 'mahasiswa',
      instagram: '@rizky_journal',
    ),
    StudentProfile(
      id: 's6',
      nim: '2210411038',
      nama: 'Tiara Amanda',
      email: 'tiara.amanda@student.unazlam.ac.id',
      noWa: '081255667788',
      peminatan: 'Public Relations',
      role: 'mahasiswa',
      instagram: '@tiaramanda',
    ),
    StudentProfile(
      id: 's7',
      nim: '2210411042',
      nama: 'Farhan Alamsyah',
      email: 'farhan.alamsyah@student.unazlam.ac.id',
      noWa: '082266778899',
      peminatan: 'Advertising',
      role: 'mahasiswa',
      instagram: '@farhan.ads',
    ),
  ];

  static final List<TreasuryTransaction> treasuryTransactions = [
    TreasuryTransaction(
      id: 't1',
      judul: 'Iuran Kas Kelas Bulan Maret (30 Mahasiswa)',
      nominal: 750000,
      isPemasukan: true,
      kategori: 'Kas Bulanan',
      tanggal: DateTime.now().subtract(const Duration(days: 3)),
      pencatat: 'Siti Nurhaliza (Bendahara)',
    ),
    TreasuryTransaction(
      id: 't2',
      judul: 'Pembelian Baterai & Memory Card SD Studio',
      nominal: 180000,
      isPemasukan: false,
      kategori: 'Sewa Studio',
      tanggal: DateTime.now().subtract(const Duration(days: 5)),
      pencatat: 'Siti Nurhaliza (Bendahara)',
    ),
    TreasuryTransaction(
      id: 't3',
      judul: 'Fotokopi Diktat Teori Komunikasi (Pertemuan 1-7)',
      nominal: 95000,
      isPemasukan: false,
      kategori: 'Fotokopi Modul',
      tanggal: DateTime.now().subtract(const Duration(days: 10)),
      pencatat: 'Irfan Maulana (Komti)',
    ),
    TreasuryTransaction(
      id: 't4',
      judul: 'Kas Awal Semester Genap',
      nominal: 975000,
      isPemasukan: true,
      kategori: 'Kas Bulanan',
      tanggal: DateTime.now().subtract(const Duration(days: 25)),
      pencatat: 'Siti Nurhaliza (Bendahara)',
    ),
  ];

  static int get totalKasSaldo {
    return treasuryTransactions.fold(0, (acc, item) {
      return item.isPemasukan ? acc + item.nominal : acc - item.nominal;
    });
  }

  static final List<StudioEquipment> studioEquipments = [
    StudioEquipment(
      id: 'eq1',
      namaAlat: 'Sony Alpha 7 IV + Lensa 24-70mm GM',
      kategori: 'Kamera & Lensa',
      isTersedia: false,
      peminjam: 'Kelompok 1 (Video Feature)',
      estimasiKembali: 'Besok, 17:00 WIB',
      lokasi: 'Studio TV Lt. 3',
    ),
    StudioEquipment(
      id: 'eq2',
      namaAlat: 'Canon EOS R6 Mark II + Lensa 50mm f/1.8',
      kategori: 'Kamera & Lensa',
      isTersedia: true,
      lokasi: 'Lemari Kamera Lab Multimedia',
    ),
    StudioEquipment(
      id: 'eq3',
      namaAlat: 'Hollyland Lark Max 2TX Wireless Mic Kit',
      kategori: 'Audio & Mic',
      isTersedia: true,
      lokasi: 'Kotak Audio Lab TV',
    ),
    StudioEquipment(
      id: 'eq4',
      namaAlat: 'Godox SL60W Continuous LED Video Light',
      kategori: 'Lighting',
      isTersedia: false,
      peminjam: 'Rizky Dwi Pratama',
      estimasiKembali: 'Hari ini, 16:30 WIB',
      lokasi: 'Studio TV & Podcast',
    ),
    StudioEquipment(
      id: 'eq5',
      namaAlat: 'Studio Podcast Akustik Ruang B',
      kategori: 'Studio Room',
      isTersedia: true,
      lokasi: 'Gedung Ilkom Lt. 2',
    ),
  ];
}
