import '../../models/models.dart';

class DummyData {
  static final List<Course> courses = [
    Course(
      id: 'c1',
      kode: '2 PK 100',
      nama: 'Pendidikan Pancasila',
      sks: 2,
      semester: 1,
      dosen: 'Drs. H. M. Rusli, M.Si',
      dosenWa: '081234567890',
      hari: 'Senin',
      jamMulai: '15:30',
      jamSelesai: '17:00',
      ruangan: 'Ruang A2',
    ),
    Course(
      id: 'c2',
      kode: '2 PK 103',
      nama: 'Pendidikan Kewarganegaraan',
      sks: 2,
      semester: 1,
      dosen: 'Dra. Hj. Nurhaida, M.Pd',
      dosenWa: '081234567891',
      hari: 'Senin',
      jamMulai: '18:30',
      jamSelesai: '20:00',
      ruangan: 'Ruang B1',
    ),
    Course(
      id: 'c3',
      kode: '3 PK 101A',
      nama: 'Pendidikan Agama Islam *',
      sks: 3,
      semester: 1,
      dosen: 'Dr. H. Lukman Hakim, M.Ag',
      dosenWa: '081234567892',
      hari: 'Selasa',
      jamMulai: '15:30',
      jamSelesai: '17:45',
      ruangan: 'Ruang A1',
    ),
    Course(
      id: 'c4',
      kode: '3 PK 101B',
      nama: 'Pendidikan Agama Kristen *',
      sks: 3,
      semester: 1,
      dosen: 'Pdt. Dr. Markus Somba, M.Th',
      dosenWa: '081234567893',
      hari: 'Selasa',
      jamMulai: '15:30',
      jamSelesai: '17:45',
      ruangan: 'Ruang B1',
    ),
    Course(
      id: 'c5',
      kode: '2 PK 106',
      nama: 'Ilmu Kealaman Dasar *',
      sks: 2,
      semester: 1,
      dosen: 'Dr. Ir. Hendra Gunawan, M.Si',
      dosenWa: '081234567894',
      hari: 'Selasa',
      jamMulai: '18:30',
      jamSelesai: '20:45',
      ruangan: 'Ruang A2',
    ),
    Course(
      id: 'c6',
      kode: '3 PK 105',
      nama: 'Bahasa Indonesia *',
      sks: 3,
      semester: 1,
      dosen: 'Dra. Hj. Nurhayati, M.Hum',
      dosenWa: '081234567895',
      hari: 'Rabu',
      jamMulai: '15:30',
      jamSelesai: '17:45',
      ruangan: 'Ruang A2',
    ),
    Course(
      id: 'c7',
      kode: '3 PK 104',
      nama: 'Bahasa Inggris *',
      sks: 3,
      semester: 1,
      dosen: 'Farid Wajdi, S.Pd., M.A',
      dosenWa: '081234567896',
      hari: 'Kamis',
      jamMulai: '18:30',
      jamSelesai: '20:45',
      ruangan: 'Ruang A1',
    ),
    Course(
      id: 'c8',
      kode: '3 PK 201',
      nama: 'Pengantar Ilmu Politik *',
      sks: 3,
      semester: 1,
      dosen: 'Dr. Muhammad Rizal, S.IP., M.Si',
      dosenWa: '081234567897',
      hari: 'Jumat',
      jamMulai: '18:30',
      jamSelesai: '20:45',
      ruangan: 'Ruang B1',
    ),
  ];

  static final List<Assignment> assignments = [
    Assignment(
      id: 'asg1',
      courseId: 'c1',
      courseName: 'Pendidikan Pancasila',
      judul: 'Makalah Analisis Nilai Pancasila dalam Media Sosial',
      deskripsi:
          'Buatlah makalah ilmiah minimal 6 halaman mengenai implementasi sila ke-2 dan sila ke-3 dalam menjaga etika berkomunikasi di media sosial (Instagram/TikTok/X). Format tulisan: Times New Roman 12, spasi 1.5, cover resmi FISIP UNAZLAM, dan daftar pustaka minimal 5 referensi jurnal.',
      kategori: 'Individu',
      deadline: DateTime.now().add(const Duration(days: 3, hours: 4)),
      linkPengumpulan: 'https://classroom.google.com/c/ilkom-unazlam-pancasila',
      status: 'sedang_dikerjakan',
    ),
    Assignment(
      id: 'asg2',
      courseId: 'c2',
      courseName: 'Pendidikan Kewarganegaraan',
      judul: 'Resume Bab 2: Hak dan Kewajiban Warga Negara di Era Otonomi Daerah',
      deskripsi:
          'Tuliskan resume kritis dari buku ajar Bab 2 mengenai harmoni hak dan kewajiban warga negara dan negara. Tambahkan contoh studi kasus penanganan fasilitas publik di Kota Palu pasca bencana. Ketik dalam format PDF 2-3 halaman.',
      kategori: 'Individu',
      deadline: DateTime.now().add(const Duration(days: 6, hours: 10)),
      linkPengumpulan: 'https://drive.google.com/drive/folders/ilkom-kewarganegaraan-unazlam',
      status: 'belum',
    ),
    Assignment(
      id: 'asg3',
      courseId: 'c5',
      courseName: 'Ilmu Kealaman Dasar *',
      judul: 'Proyek Video Liputan Dokumenter Isu Lingkungan Pesisir Teluk Palu',
      deskripsi:
          'Tugas Kelompok (4-5 orang): Lakukan wawancara dan pengambilan video lapangan terkait kebersihan pesisir, pengelolaan sampah pantai, atau ekosistem mangrove di Teluk Palu. Durasi video 3-5 menit, resolusi minimal 1080p, unggah ke Google Drive kelompok dan sertakan link pada formulir ini.',
      kategori: 'Kelompok',
      deadline: DateTime.now().add(const Duration(days: 12, hours: 8)),
      linkPengumpulan: 'https://drive.google.com/drive/folders/ilkom-ikd-telukpalu-project',
      status: 'belum',
    ),
    Assignment(
      id: 'asg4',
      courseId: 'c6',
      courseName: 'Bahasa Indonesia *',
      judul: 'Esai Argumentatif: Etika Komunikasi Digital Mahasiswa Kampus',
      deskripsi:
          'Tuliskan esai argumentatif dengan tata bahasa baku bahasa Indonesia (EYD V) tentang fenomena komunikasi daring antara mahasiswa dan dosen. Struktur esai: Pendahuluan, Tesis, Argumen Pendukung, Sanggahan, dan Kesimpulan (1000 - 1500 kata).',
      kategori: 'Individu',
      deadline: DateTime.now().add(const Duration(days: 15)),
      linkPengumpulan: 'https://classroom.google.com/c/ilkom-bahasa-indonesia',
      status: 'selesai',
    ),
    Assignment(
      id: 'asg5',
      courseId: 'c7',
      courseName: 'Bahasa Inggris *',
      judul: 'Critical Review: Interpersonal Communication in Modern Workplace',
      deskripsi:
          'Read the assigned journal article "Cross-Cultural Communication in Virtual Teams", write an analytical critique summarizing key arguments, methodology, and your personal reflection as communication science students in English.',
      kategori: 'Individu',
      deadline: DateTime.now().add(const Duration(days: 18, hours: 12)),
      linkPengumpulan: 'https://drive.google.com/drive/folders/ilkom-english-communication',
      status: 'belum',
    ),
  ];

  static final List<Announcement> announcements = [
    Announcement(
      id: 'ann1',
      authorName: 'Nur Farida (Ketua Kelas)',
      authorRole: 'Ketua Kelas',
      judul: 'PENTING: Jadwal Kuliah Semester Ganjil T.A 2026/2027 Resmi Dimulai',
      isi:
          'Halo rekan-rekan S1 Ilmu Komunikasi UNAZLAM! Perkuliahan semester ganjil telah resmi dimulai sesuai jadwal FISIP terbaru. Perhatikan jam sesi sore (15.30) dan malam (18.30) serta ruangan A1, A2, dan B1. Harap hadir 10 menit sebelum perkuliahan dimulai.',
      isPinned: true,
      kategori: 'Penting',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    Announcement(
      id: 'ann2',
      authorName: 'Akademik FISIP',
      authorRole: 'Akademik',
      judul: 'Pengambilan Kartu Rencana Studi (KRS) & Validasi SIAKAD',
      isi:
          'Diberitahukan kepada seluruh mahasiswa baru S1 Ilmu Komunikasi angkatan 2026 agar segera mencetak KRS dari portal SIAKAD UNAZLAM dan meminta tanda tangan Dosen Pembimbing Akademik (DPA) paling lambat Jumat ini.',
      isPinned: true,
      kategori: 'Akademik',
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
    ),
    Announcement(
      id: 'ann3',
      authorName: 'Farid Wajdi, S.Pd., M.A',
      authorRole: 'Dosen Pengampu',
      judul: 'Materi & Handout Perkuliahan Bahasa Inggris Pertemuan 1-3 Sudah Tersedia',
      isi:
          'Untuk seluruh mahasiswa kelas Bahasa Inggris Komunikasi, handout materi grammar & public speaking serta kisi-kisi latihan percakapan sudah diunggah di Gudang Materi. Silakan diunduh dan dipelajari sebelum sesi kuliah hari Kamis.',
      isPinned: false,
      kategori: 'Dosen',
      createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 5)),
    ),
    Announcement(
      id: 'ann4',
      authorName: 'Bendahara Kelas',
      authorRole: 'Pengurus Kelas',
      judul: 'Iuran Kas Kelas Bulan Pertama: Fotokopi Modul & Operasional Kelas',
      isi:
          'Kas kelas bulan ini disepakati sebesar Rp 20.000/mahasiswa untuk keperluan penyediaan spidol papan tulis, fotokopi lembar materi darurat, dan kas cadangan kegiatan kelas. Pembayaran dapat ditransfer via QRIS atau tunai ke bendahara.',
      isPinned: false,
      kategori: 'Kelas',
      createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 1)),
    ),
  ];

  static final List<ProjectGroup> projectGroups = [];

  static final List<CourseAttendance> attendanceRecords = [
    CourseAttendance(
      courseId: 'c1',
      courseName: 'Pendidikan Pancasila',
      sesiBerjalan: 0,
      hadir: 0,
      izin: 0,
      sakit: 0,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c2',
      courseName: 'Pendidikan Kewarganegaraan',
      sesiBerjalan: 0,
      hadir: 0,
      izin: 0,
      sakit: 0,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c3',
      courseName: 'Pendidikan Agama Islam *',
      sesiBerjalan: 0,
      hadir: 0,
      izin: 0,
      sakit: 0,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c4',
      courseName: 'Pendidikan Agama Kristen *',
      sesiBerjalan: 0,
      hadir: 0,
      izin: 0,
      sakit: 0,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c5',
      courseName: 'Ilmu Kealaman Dasar *',
      sesiBerjalan: 0,
      hadir: 0,
      izin: 0,
      sakit: 0,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c6',
      courseName: 'Bahasa Indonesia *',
      sesiBerjalan: 0,
      hadir: 0,
      izin: 0,
      sakit: 0,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c7',
      courseName: 'Bahasa Inggris *',
      sesiBerjalan: 0,
      hadir: 0,
      izin: 0,
      sakit: 0,
      alpa: 0,
    ),
    CourseAttendance(
      courseId: 'c8',
      courseName: 'Pengantar Ilmu Politik *',
      sesiBerjalan: 0,
      hadir: 0,
      izin: 0,
      sakit: 0,
      alpa: 0,
    ),
  ];

  static final List<ResourceItem> resources = [
    ResourceItem(
      id: 'res1',
      courseName: 'Pendidikan Pancasila',
      pertemuanKe: 1,
      judul: 'RPS & Slide Pertemuan 1 - Urgensi Nilai Pancasila di Era Digital',
      jenis: 'Slide PPT',
      linkUrl: 'https://docs.google.com/presentation/d/1unazlam-pancasila-ppt1/edit',
    ),
    ResourceItem(
      id: 'res2',
      courseName: 'Pendidikan Kewarganegaraan',
      pertemuanKe: 2,
      judul: 'Modul Buku Ajar: Hak & Kewajiban Warga Negara Indonesia',
      jenis: 'E-Book',
      linkUrl: 'https://drive.google.com/file/d/1unazlam-kewarganegaraan-modul/view',
    ),
    ResourceItem(
      id: 'res3',
      courseName: 'Bahasa Indonesia *',
      pertemuanKe: 1,
      judul: 'Pedoman Umum Ejaan Bahasa Indonesia (EYD V) & Sitasi Ilmiah',
      jenis: 'E-Book',
      linkUrl: 'https://drive.google.com/file/d/1unazlam-eyd-pedoman/view',
    ),
    ResourceItem(
      id: 'res4',
      courseName: 'Ilmu Kealaman Dasar *',
      pertemuanKe: 3,
      judul: 'Jurnal Penelitian: Ekosistem Teluk Palu dan Konservasi Pesisir',
      jenis: 'Jurnal Ilmiah',
      linkUrl: 'https://journal.unazlam.ac.id/ikd-teluk-palu-paper.pdf',
    ),
    ResourceItem(
      id: 'res5',
      courseName: 'Bahasa Inggris *',
      pertemuanKe: 2,
      judul: 'Handout: Essential Business & Communication English Phrases',
      jenis: 'Slide PPT',
      linkUrl: 'https://docs.google.com/presentation/d/1unazlam-english-handout/edit',
    ),
    ResourceItem(
      id: 'res6',
      courseName: 'Pengantar Ilmu Politik *',
      pertemuanKe: 1,
      judul: 'Bank Soal Latihan & Kasus Kajian Komunikasi Politik Kontemporer',
      jenis: 'Bank Soal',
      linkUrl: 'https://drive.google.com/file/d/1unazlam-bank-soal-politik/view',
    ),
  ];

  static final List<StudentProfile> students = [
    StudentProfile(
      id: 'adm1',
      nim: 'admin',
      nama: 'ADMINISTRATOR SISTEM',
      email: 'admin.ilkom@unazlam.ac.id',
      noWa: '081234567890',
      role: 'ADMIN',
      jabatan: 'System Administrator',
      prodi: 'Ilmu Komunikasi',
      semester: 1,
      kelas: 'Fakultas FISIP UNAZLAM',
      instagram: '@ilkom.unazlam',
    ),
    StudentProfile(
      id: 's1',
      nim: '260250001',
      nama: 'HAPPY HELEN ANDINI',
      email: '260250001@student.unazlam.ac.id',
      noWa: '081241000101',
      role: 'MAHASISWA',
      jabatan: 'Mahasiswa',
      instagram: '@happy.helen',
    ),
    StudentProfile(
      id: 's2',
      nim: '260250003',
      nama: 'STELA GLORI. B',
      email: '260250003@student.unazlam.ac.id',
      noWa: '081241000102',
      role: 'MAHASISWA',
      jabatan: 'Mahasiswa',
      instagram: '@stelaglori',
    ),
    StudentProfile(
      id: 's3',
      nim: '260250004',
      nama: 'SINAR WAHYUNI',
      email: '260250004@student.unazlam.ac.id',
      noWa: '081241000103',
      role: 'MAHASISWA',
      jabatan: 'Wakil Ketua',
      instagram: '@sinar.wahyuni',
    ),
    StudentProfile(
      id: 's4',
      nim: '260250006',
      nama: 'ANDI SUCI AMALIA RAMADHANI',
      email: '260250006@student.unazlam.ac.id',
      noWa: '081241000104',
      role: 'MAHASISWA',
      jabatan: 'Mahasiswa',
      instagram: '@andisuciamalia',
    ),
    StudentProfile(
      id: 's5',
      nim: '260250008',
      nama: 'STEFANI',
      email: '260250008@student.unazlam.ac.id',
      noWa: '081241000105',
      role: 'MAHASISWA',
      jabatan: 'Sekretaris',
      instagram: '@stefani_comm',
    ),
    StudentProfile(
      id: 's6',
      nim: '260250009',
      nama: 'ARIEF PRAYUDHA RAMADHANSYAH',
      email: '260250009@student.unazlam.ac.id',
      noWa: '081241000106',
      role: 'mahasiswa',
      instagram: '@arief.prayudha',
    ),
    StudentProfile(
      id: 's7',
      nim: '260250011',
      nama: 'ALIFIA NASYAH RAMADANI',
      email: '260250011@student.unazlam.ac.id',
      noWa: '081241000107',
      role: 'mahasiswa',
      instagram: '@alifia.nasyah',
    ),
    StudentProfile(
      id: 's8',
      nim: '260250014',
      nama: 'SUSIAN',
      email: '260250014@student.unazlam.ac.id',
      noWa: '081241000108',
      role: 'mahasiswa',
      instagram: '@susian_ilkom',
    ),
    StudentProfile(
      id: 's9',
      nim: '260250015',
      nama: 'PUTRI SYAFWAH',
      email: '260250015@student.unazlam.ac.id',
      noWa: '081241000109',
      role: 'mahasiswa',
      instagram: '@putri.syafwah',
    ),
    StudentProfile(
      id: 's10',
      nim: '260250017',
      nama: 'DONI FERNANDO',
      email: '260250017@student.unazlam.ac.id',
      noWa: '081241000110',
      role: 'mahasiswa',
      instagram: '@doni.fernando',
    ),
    StudentProfile(
      id: 's11',
      nim: '260250018',
      nama: 'CELSI APRILIA',
      email: '260250018@student.unazlam.ac.id',
      noWa: '081241000111',
      role: 'mahasiswa',
      instagram: '@celsi.aprilia',
    ),
    StudentProfile(
      id: 's12',
      nim: '260250019',
      nama: 'NAZWA TRI AULIA',
      email: '260250019@student.unazlam.ac.id',
      noWa: '081241000112',
      role: 'mahasiswa',
      instagram: '@nazwatriaulia',
    ),
    StudentProfile(
      id: 's13',
      nim: '260250020',
      nama: "ALYA NABILAH NA'ILAH",
      email: '260250020@student.unazlam.ac.id',
      noWa: '081241000113',
      role: 'MAHASISWA',
      jabatan: 'Bendahara',
      instagram: '@alyanabilah',
    ),
    StudentProfile(
      id: 's14',
      nim: '260250022',
      nama: 'VALENTINO',
      email: '260250022@student.unazlam.ac.id',
      noWa: '081241000114',
      role: 'MAHASISWA',
      jabatan: 'Mahasiswa',
      instagram: '@valentino_comm',
    ),
    StudentProfile(
      id: 's15',
      nim: '260250023',
      nama: 'NUR FARIDA',
      email: '260250023@student.unazlam.ac.id',
      noWa: '081241000115',
      role: 'MAHASISWA',
      jabatan: 'Ketua Kelas',
      instagram: '@nur.farida',
    ),
    StudentProfile(
      id: 's16',
      nim: '260250026',
      nama: 'WIRDAH RATU SABRINA',
      email: '260250026@student.unazlam.ac.id',
      noWa: '081241000116',
      role: 'MAHASISWA',
      jabatan: 'Mahasiswa',
      instagram: '@wirdahratusabrina',
    ),
    StudentProfile(
      id: 's17',
      nim: '260250027',
      nama: 'ALFEUS',
      email: '260250027@student.unazlam.ac.id',
      noWa: '081241000117',
      role: 'mahasiswa',
      instagram: '@alfeus_comm',
    ),
    StudentProfile(
      id: 's18',
      nim: '260250030',
      nama: 'AFRYLIYANA',
      email: '260250030@student.unazlam.ac.id',
      noWa: '081241000118',
      role: 'mahasiswa',
      instagram: '@afryliyana',
    ),
    StudentProfile(
      id: 's19',
      nim: '260250031',
      nama: 'TASYA',
      email: '260250031@student.unazlam.ac.id',
      noWa: '081241000119',
      role: 'mahasiswa',
      instagram: '@tasya_ilkom',
    ),
    StudentProfile(
      id: 's20',
      nim: '260250034',
      nama: 'AULIA RAHMA',
      email: '260250034@student.unazlam.ac.id',
      noWa: '081241000120',
      role: 'MAHASISWA',
      jabatan: 'Bendahara 2',
      instagram: '@aulia.rahma',
    ),
    StudentProfile(
      id: 's21',
      nim: '260250035',
      nama: 'SHOFA AZZAHRA',
      email: '260250035@student.unazlam.ac.id',
      noWa: '081241000121',
      role: 'MAHASISWA',
      jabatan: 'Mahasiswa',
      instagram: '@shofa.azzahra',
    ),
    StudentProfile(
      id: 's22',
      nim: '260250012',
      nama: 'GILANG RAMADHAN',
      email: '260250012@student.unazlam.ac.id',
      noWa: '081241000122',
      role: 'MAHASISWA',
      jabatan: 'Koordinator Perlengkapan',
      instagram: '@gilang.ramadhan',
    ),
    StudentProfile(
      id: 's23',
      nim: '260250025',
      nama: 'ALIEF PUTRA RAMADHAN',
      email: '260250025@student.unazlam.ac.id',
      noWa: '081241000123',
      role: 'MAHASISWA',
      jabatan: 'Mahasiswa',
      instagram: '@alief.putra',
    ),
  ];

  static final List<TreasuryTransaction> treasuryTransactions = [
    TreasuryTransaction(
      id: 'tx_1',
      judul: 'Iuran Kas Bulan Oktober',
      nominal: 250000,
      isPemasukan: true,
      kategori: 'Iuran Kelas',
      tanggal: DateTime(2026, 10, 5),
      pencatat: 'Alya Nabilah (Bendahara)',
    ),
    TreasuryTransaction(
      id: 'tx_2',
      judul: 'Cetak Dokumen & Spanduk Kelas',
      nominal: 50000,
      isPemasukan: false,
      kategori: 'Perlengkapan',
      tanggal: DateTime(2026, 10, 3),
      pencatat: 'Alya Nabilah (Bendahara)',
    ),
    TreasuryTransaction(
      id: 'tx_3',
      judul: 'Saldo Awal Kas Semester 1',
      nominal: 500000,
      isPemasukan: true,
      kategori: 'Iuran Kelas',
      tanggal: DateTime(2026, 9, 28),
      pencatat: 'Alya Nabilah (Bendahara)',
    ),
    TreasuryTransaction(
      id: 'tx_4',
      judul: 'Pembelian Alat Kebersihan & ATK Kelas',
      nominal: 450000,
      isPemasukan: false,
      kategori: 'Operasional',
      tanggal: DateTime(2026, 9, 20),
      pencatat: 'Alya Nabilah (Bendahara)',
    ),
    TreasuryTransaction(
      id: 'tx_5',
      judul: 'Iuran Praktikum Broadcasting',
      nominal: 500000,
      isPemasukan: true,
      kategori: 'Iuran Praktikum',
      tanggal: DateTime(2026, 9, 15),
      pencatat: 'Alya Nabilah (Bendahara)',
    ),
  ];

  static int get totalKasSaldo {
    return treasuryTransactions.fold(0, (acc, item) {
      return item.isPemasukan ? acc + item.nominal : acc - item.nominal;
    });
  }

  static final List<StudioEquipment> studioEquipments = [];
}
